#+title: czm-cpp.el: Helper functions for working with C++ projects
#+author: Paul Nelson

* Overview
This package contains some helper functions for working with C++ projects.  For example, the package contains a template CMake project and a helper function, =czm-cpp-new-project-scratch=, for copying that template to a new "scratch" folder.  There's also a helper function, =czm-cpp-init-header=, which inserts an appropriate header guard at the top of a header file.

* Configuration
This package requires (my fork of) [[https://github.com/ultronozm/cmake-build.el][cmake-build.el]], so install that first.

Download this repository, install using =M-x package-install-file= (or package-vc-install, straight, elpaca, ...), and add something like the following to your [[https://www.emacswiki.org/emacs/InitFile][init file]]:

#+begin_src elisp
(use-package czm-cpp
  :custom
  (czm-cpp-scratch-directory "~/scratch/cpp"))
#+end_src

Replace the path with the folder where you want scratch C++ projects stored.

I use [[https://github.com/progfolio/elpaca][elpaca]], with something like the following in my init file:

#+begin_src elisp
(use-package czm-cpp
  :ensure (:host github :repo "ultronozm/czm-cpp.el"
                 :files ("*.el" "template")
                 :depth nil)
  :custom
  (czm-cpp-scratch-directory "~/scratch/cpp"))
#+end_src

Use the built-in documentation (=C-h f czm-cpp-whatever=) to see what the various commands do.
